# -*- coding: utf-8 -*-
"""ArmstrongNO.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rM9VcVjIV89OX0GL_DZDZT9UeADceoqh
"""

def count_digit(n):
    count = 0
    while n:
        n //= 10
        count += 1
    return count

# Function to check Armstrong
def is_armstrong(n):

    if n< 0:
        return False
    
    number_copy = n
    arm_sum = 0
    digit = count_digit(n)
    while n:
        remainder = n%10
        arm_sum += remainder**digit
        n //= 10

    return arm_sum == number_copy



# Reading interval from user
min_value = int(input('Enter minimum value: '))
max_value = int(input('Enter maximum value: '))

# Looping & displaying if it is Armstrong
# Here min_vale & max_value are included
print('Armstrong numbers from %d to %d are:' %(min_value, max_value))
for i in range(min_value, max_value+1):
    if is_armstrong(i):
        print(i, end=' ')