# -*- coding: utf-8 -*-
"""Non-linear regression.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K3jp44i-ev60azcwfnEZUuGy1cxxz-Bd
"""

pip install popt

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# downloading dataset
! wget -nv -O china_gdp.csv https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data / CognitiveClass / ML0101ENv3 / labs / china_gdp.csv
	
df = pd.read_csv("china_gdp.csv")

def sigmoid(x, Beta_1, Beta_2):
	y = 1 / (1 + np.exp(-Beta_1*(x-Beta_2)))
	return y
	
x = np.linspace(1960, 2015, 55)
x = x / max(x)
y = sigmoid(x, *popt)

plt.figure(figsize =(8, 5))
plt.plot(xdata, ydata, 'ro', label ='data')
plt.plot(x, y, linewidth = 3.0, label ='fit')
plt.legend(loc ='best')
plt.ylabel('GDP')
plt.xlabel('Year')
plt.show()