# -*- coding: utf-8 -*-
"""special symbol.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-oSqdhay7DV45TjbUeLGNPCv50TTeEKK
"""

import math

π = math.pi
class Spin̈alTap: pass
Spin̈alTap()