# -*- coding: utf-8 -*-
"""String find().ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IDG0EWnAdvet4ijbsryDU3he9l4U6oT5

Here, a sample python program is given, which will explain how find() function will works:
"""

our_string = 'Python Stack Hub Python Stack Hub'
our_string.find('Stack', 10, 33)

"""# If only the starting index is given then this method will assign len(string) as end """

our_string = 'Python Stack Hub Python Stack Hub'
our_string.find('Stack', 10)

"""The find() method uses case-sensitive search to find the sub-string in the given string, so in the below example it will only return the starting index of 'Stack',"""

our_string = 'Python stack Hub python Stack hub'
our_string.find('Stack')

"""If the sub-string was not found in the given string then this method will return -1 without throwing an error. Let us check this in the example given below."""

our_string = 'Python stack Hub python Stack hub'
our_string.find('invisible')

